"""add team and team_member

Revision ID: 04fcb161b253
Revises: 2d05fabe0ea9
Create Date: 2026-01-09 14:17:53.303560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04fcb161b253'
down_revision: Union[str, Sequence[str], None] = '2d05fabe0ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homework_submissions_owner_id'), table_name='homework_submissions')
    op.drop_constraint(op.f('homework_submissions_owner_id_fkey'), 'homework_submissions', type_='foreignkey')
    op.drop_column('homework_submissions', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_submissions', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('homework_submissions_owner_id_fkey'), 'homework_submissions', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_homework_submissions_owner_id'), 'homework_submissions', ['owner_id'], unique=False)
    # ### end Alembic commands ###
