"""add team and team_me1

Revision ID: 053e3c2e8527
Revises: 71e30cee170e
Create Date: 2026-01-09 21:00:59.038827

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "053e3c2e8527"
down_revision: str | Sequence[str] | None = "71e30cee170e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
