"""change date to datetime for activities

Revision ID: 0553d55b6399
Revises: 609a56bbee52
Create Date: 2026-01-07 20:49:02.239614

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0553d55b6399"
down_revision: str | Sequence[str] | None = "609a56bbee52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
