"""add indexes

Revision ID: 1533e4e0432b
Revises: 7e6084ddbc24
Create Date: 2026-01-18 03:59:18.350180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1533e4e0432b'
down_revision: Union[str, Sequence[str], None] = '7e6084ddbc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_bonus_points_created_at'), 'bonus_points', ['created_at'], unique=False)
    op.create_index(op.f('ix_homework_submissions_created_at'), 'homework_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_homework_submissions_status'), 'homework_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_homeworks_created_at'), 'homeworks', ['created_at'], unique=False)
    op.create_index(op.f('ix_homeworks_deadline'), 'homeworks', ['deadline'], unique=False)
    op.create_index(op.f('ix_permission_requests_created_at'), 'permission_requests', ['created_at'], unique=False)
    op.create_index('ix_permission_requests_created_by', 'permission_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_permission_requests_date'), 'permission_requests', ['date'], unique=False)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_role_permissions_created_at'), 'role_permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_members_created_at'), 'team_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_violations_created_at'), 'violations', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_created_at'), table_name='violations')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_index(op.f('ix_team_members_created_at'), table_name='team_members')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_index(op.f('ix_role_permissions_created_at'), table_name='role_permissions')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_permission_requests_date'), table_name='permission_requests')
    op.drop_index('ix_permission_requests_created_by', table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_created_at'), table_name='permission_requests')
    op.drop_index(op.f('ix_homeworks_deadline'), table_name='homeworks')
    op.drop_index(op.f('ix_homeworks_created_at'), table_name='homeworks')
    op.drop_index(op.f('ix_homework_submissions_status'), table_name='homework_submissions')
    op.drop_index(op.f('ix_homework_submissions_created_at'), table_name='homework_submissions')
    op.drop_index(op.f('ix_bonus_points_created_at'), table_name='bonus_points')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    # ### end Alembic commands ###
