"""remove_date_from_permission_request

Revision ID: 182b05fa9ef9
Revises: c17079fb4333
Create Date: 2026-04-08 02:17:18.842543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "182b05fa9ef9"
down_revision: Union[str, Sequence[str], None] = "c17079fb4333"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_permission_requests_date"), table_name="permission_requests")
    op.drop_column("permission_requests", "date")
    op.alter_column(
        "role_api_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "role_api_keys",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "role_api_keys", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False
    )
    # op.drop_index(op.f('ix_role_api_keys_prefix'), table_name='role_api_keys')
    op.create_foreign_key(None, "role_api_keys", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "role_api_keys", "users", ["updated_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role_api_keys", type_="foreignkey")
    op.drop_constraint(None, "role_api_keys", type_="foreignkey")
    op.create_index(
        op.f("ix_role_api_keys_prefix"), "role_api_keys", ["prefix"], unique=False
    )
    op.alter_column(
        "role_api_keys", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "role_api_keys",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "role_api_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.add_column(
        "permission_requests",
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_permission_requests_date"),
        "permission_requests",
        ["date"],
        unique=False,
    )
    # ### end Alembic commands ###
