"""add monthly_user_stats table

Revision ID: 2e45ea41c61a
Revises: cce51408a625
Create Date: 2026-05-07 10:40:38.722728

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2e45ea41c61a"
down_revision: str | Sequence[str] | None = "cce51408a625"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
