"""add updated_by for all table

Revision ID: 3ffe5a794212
Revises: 0553d55b6399
Create Date: 2026-01-08 16:01:10.149475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3ffe5a794212"
down_revision: Union[str, Sequence[str], None] = "0553d55b6399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.alter_column("accounts", "created_by", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "accounts", "users", ["updated_by"], ["id"])
    op.add_column("bonus_points", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.alter_column(
        "bonus_points", "created_by", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(None, "bonus_points", "users", ["updated_by"], ["id"])
    op.add_column(
        "permission_requests", sa.Column("updated_by", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "permission_requests", "created_by", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(None, "permission_requests", "users", ["updated_by"], ["id"])
    op.add_column("permissions", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.alter_column(
        "permissions", "created_by", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(None, "permissions", "users", ["updated_by"], ["id"])
    op.add_column(
        "role_permissions", sa.Column("updated_by", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "role_permissions", "created_by", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(None, "role_permissions", "users", ["updated_by"], ["id"])
    op.add_column("roles", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.alter_column("roles", "created_by", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "roles", "users", ["updated_by"], ["id"])
    op.add_column("users", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.alter_column("users", "created_by", existing_type=sa.INTEGER(), nullable=True)
    op.create_foreign_key(None, "users", "users", ["updated_by"], ["id"])
    op.add_column("violations", sa.Column("updated_by", sa.Integer(), nullable=True))
    op.alter_column(
        "violations", "created_by", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_foreign_key(None, "violations", "users", ["updated_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "violations", type_="foreignkey")
    op.alter_column(
        "violations", "created_by", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("violations", "updated_by")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.alter_column("users", "created_by", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("users", "updated_by")
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.alter_column("roles", "created_by", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("roles", "updated_by")
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.alter_column(
        "role_permissions", "created_by", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("role_permissions", "updated_by")
    op.drop_constraint(None, "permissions", type_="foreignkey")
    op.alter_column(
        "permissions", "created_by", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("permissions", "updated_by")
    op.drop_constraint(None, "permission_requests", type_="foreignkey")
    op.alter_column(
        "permission_requests", "created_by", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("permission_requests", "updated_by")
    op.drop_constraint(None, "bonus_points", type_="foreignkey")
    op.alter_column(
        "bonus_points", "created_by", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("bonus_points", "updated_by")
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.alter_column(
        "accounts", "created_by", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("accounts", "updated_by")
    # ### end Alembic commands ###
