"""add_client_event_id_to_meeting_participants

Revision ID: 4405c56add67
Revises: 226397f44e99
Create Date: 2026-06-23 12:20:30.180389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4405c56add67'
down_revision: Union[str, Sequence[str], None] = '226397f44e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('homeworks', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('meeting_participants', sa.Column('client_event_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_meeting_participants_client_event_id'), 'meeting_participants', ['client_event_id'], unique=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_meeting_participants_client_event_id'), table_name='meeting_participants')
    op.drop_column('meeting_participants', 'client_event_id')
    op.alter_column('homeworks', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
