"""

Revision ID: 4790a2b574fc
Revises: d1e2f3a4b5c6
Create Date: 2026-09-25 16:24:26.341438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4790a2b574fc'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_team_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'teams', ['team_id'], ['id'])
    op.drop_index(op.f('monthly_user_stats_user_id_month_year_key'), table_name='monthly_user_stats')
    op.create_unique_constraint(None, 'monthly_user_stats', ['user_id', 'month', 'year'])
    op.alter_column('outgoing_invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('outgoing_invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_outgoing_invoices_created_at'), 'outgoing_invoices', ['created_at'], unique=False)
    op.drop_constraint(op.f('outgoing_invoices_team_id_fkey'), 'outgoing_invoices', type_='foreignkey')
    op.drop_constraint(op.f('outgoing_invoices_spender_id_fkey'), 'outgoing_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'outgoing_invoices', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'outgoing_invoices', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'outgoing_invoices', 'users', ['spender_id'], ['id'])
    op.create_foreign_key(None, 'outgoing_invoices', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outgoing_invoices', type_='foreignkey')
    op.drop_constraint(None, 'outgoing_invoices', type_='foreignkey')
    op.drop_constraint(None, 'outgoing_invoices', type_='foreignkey')
    op.drop_constraint(None, 'outgoing_invoices', type_='foreignkey')
    op.create_foreign_key(op.f('outgoing_invoices_spender_id_fkey'), 'outgoing_invoices', 'users', ['spender_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('outgoing_invoices_team_id_fkey'), 'outgoing_invoices', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_outgoing_invoices_created_at'), table_name='outgoing_invoices')
    op.alter_column('outgoing_invoices', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('outgoing_invoices', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'monthly_user_stats', type_='unique')
    op.create_index(op.f('monthly_user_stats_user_id_month_year_key'), 'monthly_user_stats', ['user_id', 'month', 'year'], unique=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_team_id_fkey'), 'invoices', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
