"""

Revision ID: 4fbab330538b
Revises: 51abe17bcad4
Create Date: 2026-01-24 05:47:55.907122

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4fbab330538b"
down_revision: Union[str, Sequence[str], None] = "51abe17bcad4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "discord_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.create_index(op.f("ix_users_discord_id"), "users", ["discord_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_discord_id"), table_name="users")
    op.drop_column("users", "discord_id")
    # ### end Alembic commands ###
