"""add meeting and meeting_participant tables

Revision ID: 51abe17bcad4
Revises: 4604c5a5dee4
Create Date: 2026-01-20 15:00:12.934827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "51abe17bcad4"
down_revision: Union[str, Sequence[str], None] = "4604c5a5dee4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meetings",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "content", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meetings_created_at"), "meetings", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_meetings_end_time"), "meetings", ["end_time"], unique=False
    )
    op.create_index(
        op.f("ix_meetings_start_time"), "meetings", ["start_time"], unique=False
    )
    op.create_table(
        "meeting_participants",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("check_in_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NOT_JOINED", "JOINED", name="participantstatus"),
            nullable=False,
        ),
        sa.Column(
            "link_image", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meeting_participants_created_at"),
        "meeting_participants",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_participants_meeting_id"),
        "meeting_participants",
        ["meeting_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meeting_participants_user_id"),
        "meeting_participants",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_meeting_participants_user_id"), table_name="meeting_participants"
    )
    op.drop_index(
        op.f("ix_meeting_participants_meeting_id"), table_name="meeting_participants"
    )
    op.drop_index(
        op.f("ix_meeting_participants_created_at"), table_name="meeting_participants"
    )
    op.drop_table("meeting_participants")
    op.drop_index(op.f("ix_meetings_start_time"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_end_time"), table_name="meetings")
    op.drop_index(op.f("ix_meetings_created_at"), table_name="meetings")
    op.drop_table("meetings")
    # ### end Alembic commands ###
