"""add created_by to TimestampMixin

Revision ID: 609a56bbee52
Revises: 652f96f7da3b
Create Date: 2026-01-07 20:38:51.094289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "609a56bbee52"
down_revision: Union[str, Sequence[str], None] = "652f96f7da3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Accounts
    op.add_column("accounts", sa.Column("created_by", sa.Integer(), nullable=True))
    op.execute("UPDATE accounts SET created_by = 1 WHERE created_by IS NULL")
    op.alter_column("accounts", "created_by", nullable=False)
    op.create_foreign_key(None, "accounts", "users", ["created_by"], ["id"])

    # 2. Bonus Points
    op.add_column("bonus_points", sa.Column("created_by", sa.Integer(), nullable=True))
    op.execute("UPDATE bonus_points SET created_by = 1 WHERE created_by IS NULL")
    op.alter_column("bonus_points", "created_by", nullable=False)
    op.create_foreign_key(None, "bonus_points", "users", ["created_by"], ["id"])

    # 3. Permission Requests
    op.add_column(
        "permission_requests", sa.Column("created_by", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE permission_requests SET created_by = 1 WHERE created_by IS NULL")
    op.alter_column("permission_requests", "created_by", nullable=False)
    op.create_foreign_key(None, "permission_requests", "users", ["created_by"], ["id"])

    # 4. Permissions
    op.add_column("permissions", sa.Column("created_by", sa.Integer(), nullable=True))
    op.execute("UPDATE permissions SET created_by = 1 WHERE created_by IS NULL")
    op.alter_column("permissions", "created_by", nullable=False)
    op.create_foreign_key(None, "permissions", "users", ["created_by"], ["id"])

    # 5. Role Permissions
    op.add_column(
        "role_permissions", sa.Column("created_by", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE role_permissions SET created_by = 1 WHERE created_by IS NULL")
    op.alter_column("role_permissions", "created_by", nullable=False)
    op.create_foreign_key(None, "role_permissions", "users", ["created_by"], ["id"])

    # 6. Roles
    op.add_column("roles", sa.Column("created_by", sa.Integer(), nullable=True))
    op.execute("UPDATE roles SET created_by = 1 WHERE created_by IS NULL")
    op.alter_column("roles", "created_by", nullable=False)
    op.create_foreign_key(None, "roles", "users", ["created_by"], ["id"])

    # 7. Users
    op.add_column("users", sa.Column("created_by", sa.Integer(), nullable=True))
    op.execute("UPDATE users SET created_by = 1 WHERE created_by IS NULL")
    op.alter_column("users", "created_by", nullable=False)
    op.create_foreign_key(None, "users", "users", ["created_by"], ["id"])

    # 8. Violations
    op.add_column("violations", sa.Column("created_by", sa.Integer(), nullable=True))
    op.execute("UPDATE violations SET created_by = 1 WHERE created_by IS NULL")
    op.alter_column("violations", "created_by", nullable=False)
    op.create_foreign_key(None, "violations", "users", ["created_by"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "violations", type_="foreignkey")
    op.drop_column("violations", "created_by")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "created_by")
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.drop_column("roles", "created_by")
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.drop_column("role_permissions", "created_by")
    op.drop_constraint(None, "permissions", type_="foreignkey")
    op.drop_column("permissions", "created_by")
    op.drop_constraint(None, "permission_requests", type_="foreignkey")
    op.drop_column("permission_requests", "created_by")
    op.drop_constraint(None, "bonus_points", type_="foreignkey")
    op.drop_column("bonus_points", "created_by")
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.drop_column("accounts", "created_by")
    # ### end Alembic commands ###
