"""change_homework_status_to_string

Revision ID: 6706609c25d4
Revises: 4291020226ce
Create Date: 2026-01-09 21:06:28.794714

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6706609c25d4"
down_revision: str | Sequence[str] | None = "4291020226ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "homework_submissions",
        "status",
        existing_type=postgresql.ENUM(
            "NOT_SUBMITTED",
            "SUBMITTED",
            "PENDING_LEADER_REVIEW",
            "PENDING_ADMIN_REVIEW",
            "FINISHED",
            "leader đã check",
            "LEADER_CHECKED",
            name="homeworkstatus",
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "homework_submissions",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "NOT_SUBMITTED",
            "SUBMITTED",
            "PENDING_LEADER_REVIEW",
            "PENDING_ADMIN_REVIEW",
            "FINISHED",
            "leader đã check",
            "LEADER_CHECKED",
            name="homeworkstatus",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
