"""add requires_coding and requires_game to homeworks

Revision ID: 6a13dfe16856
Revises: a4ae1ae2cbe2
Create Date: 2026-10-04 23:22:29.276104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a13dfe16856'
down_revision: Union[str, Sequence[str], None] = 'a4ae1ae2cbe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('requires_coding', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('homeworks', sa.Column('requires_game', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'requires_game')
    op.drop_column('homeworks', 'requires_coding')
    # ### end Alembic commands ###
