"""add team and team_member

Revision ID: 71e30cee170e
Revises: 34d5f201eeab
Create Date: 2026-01-09 20:59:42.245000

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "71e30cee170e"
down_revision: str | Sequence[str] | None = "34d5f201eeab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
