"""add_file_url_to_homework

Revision ID: 757d8bc68a8a
Revises: eeebfcde1369
Create Date: 2026-01-28 14:21:47.456079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '757d8bc68a8a'
down_revision: Union[str, Sequence[str], None] = 'eeebfcde1369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homeworks', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homeworks', 'file_url')
    # ### end Alembic commands ###
