"""add_owner_id_and_drop_homework_assignees

Revision ID: 7e6084ddbc24
Revises: 6a76bbb01f68
Create Date: 2026-01-11 16:50:11.700979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e6084ddbc24'
down_revision: Union[str, Sequence[str], None] = '6a76bbb01f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homework_assignees')
    op.add_column('homework_submissions', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_homework_submissions_owner_id'), 'homework_submissions', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'homework_submissions', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homework_submissions', type_='foreignkey')
    op.drop_index(op.f('ix_homework_submissions_owner_id'), table_name='homework_submissions')
    op.drop_column('homework_submissions', 'owner_id')
    op.create_table('homework_assignees',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('homework_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('homework_assignees_created_by_fkey')),
    sa.ForeignKeyConstraint(['homework_id'], ['homeworks.id'], name=op.f('homework_assignees_homework_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('homework_assignees_updated_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('homework_assignees_user_id_fkey')),
    sa.PrimaryKeyConstraint('homework_id', 'user_id', name=op.f('homework_assignees_pkey'))
    )
    # ### end Alembic commands ###
