"""refactor_permission_request

Revision ID: 823b59b28035
Revises: 8509ea4859ec
Create Date: 2026-04-03 06:22:08.745912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '823b59b28035'
down_revision: Union[str, Sequence[str], None] = '8509ea4859ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_requests', sa.Column('homework_id', sa.Integer(), nullable=True))
    op.add_column('permission_requests', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.alter_column('permission_requests', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.create_index(op.f('ix_permission_requests_homework_id'), 'permission_requests', ['homework_id'], unique=False)
    op.create_index(op.f('ix_permission_requests_meeting_id'), 'permission_requests', ['meeting_id'], unique=False)
    op.create_foreign_key(None, 'permission_requests', 'homeworks', ['homework_id'], ['id'])
    op.create_foreign_key(None, 'permission_requests', 'meetings', ['meeting_id'], ['id'])
    op.drop_column('permission_requests', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_requests', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'permission_requests', type_='foreignkey')
    op.drop_constraint(None, 'permission_requests', type_='foreignkey')
    op.drop_index(op.f('ix_permission_requests_meeting_id'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_homework_id'), table_name='permission_requests')
    op.alter_column('permission_requests', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_column('permission_requests', 'meeting_id')
    op.drop_column('permission_requests', 'homework_id')
    # ### end Alembic commands ###
