"""move account_id from user to auth as user_id

Revision ID: 8509ea4859ec
Revises: e8f2a1c0b3d4
Create Date: 2026-04-02 15:45:01.765779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8509ea4859ec"
down_revision: Union[str, Sequence[str], None] = "e8f2a1c0b3d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("user_id", sa.Integer(), nullable=True))

    # Data migration: Move id from users.account_id to accounts.user_id
    op.execute(
        "UPDATE accounts SET user_id = users.id FROM users WHERE users.account_id = accounts.id"
    )

    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=True)
    op.create_foreign_key(None, "accounts", "users", ["user_id"], ["id"])
    op.drop_constraint("users_account_id_key", "users", type_="unique")
    op.drop_constraint("users_account_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "account_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("account_id", sa.Integer(), autoincrement=False, nullable=True),
    )

    # Data migration: Move id from accounts.user_id back to users.account_id
    op.execute(
        "UPDATE users SET account_id = accounts.id FROM accounts WHERE accounts.user_id = users.id"
    )

    op.create_foreign_key(
        "users_account_id_fkey", "users", "accounts", ["account_id"], ["id"]
    )
    op.create_unique_constraint("users_account_id_key", "users", ["account_id"])
    op.drop_constraint(None, "accounts", type_="foreignkey")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_column("accounts", "user_id")
    # ### end Alembic commands ###
