"""change_start_time_to_datetime_for_permission

Revision ID: 85f966468765
Revises: 182b05fa9ef9
Create Date: 2026-04-08 04:29:01.806791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85f966468765'
down_revision: Union[str, Sequence[str], None] = '182b05fa9ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission_requests', 'start_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using='created_at::date + start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission_requests', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
