"""add feedback to submission

Revision ID: 88fd33baf664
Revises: 85f966468765
Create Date: 2026-04-10 17:24:20.195981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88fd33baf664'
down_revision: Union[str, Sequence[str], None] = '85f966468765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_submissions', sa.Column('is_pass', sa.Boolean(), nullable=True))
    op.add_column('homework_submissions', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('homework_submissions', sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('homework_submissions', sa.Column('score_details', sa.JSON(), nullable=True))
    op.add_column('homework_submissions', sa.Column('plagiarism_info', sa.JSON(), nullable=True))
    op.add_column('homework_submissions', sa.Column('is_plagiarized', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('homework_submissions', sa.Column('plagiarized_from_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'homework_submissions', 'users', ['plagiarized_from_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'homework_submissions', type_='foreignkey')
    op.drop_column('homework_submissions', 'plagiarized_from_user_id')
    op.drop_column('homework_submissions', 'is_plagiarized')
    op.drop_column('homework_submissions', 'plagiarism_info')
    op.drop_column('homework_submissions', 'score_details')
    op.drop_column('homework_submissions', 'feedback')
    op.drop_column('homework_submissions', 'score')
    op.drop_column('homework_submissions', 'is_pass')
    # ### end Alembic commands ###
