"""add team and team_member

Revision ID: 8c729ccd9345
Revises: 10e21272fa32
Create Date: 2026-01-09 13:07:43.548460

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8c729ccd9345"
down_revision: Union[str, Sequence[str], None] = "10e21272fa32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_permission_requests_user_id"), table_name="permission_requests"
    )
    op.drop_constraint(
        op.f("permission_requests_user_id_fkey"),
        "permission_requests",
        type_="foreignkey",
    )
    op.drop_column("permission_requests", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permission_requests",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("permission_requests_user_id_fkey"),
        "permission_requests",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_permission_requests_user_id"),
        "permission_requests",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
