"""remove deadline

Revision ID: a4ae1ae2cbe2
Revises: c4e5f6a7b8c9
Create Date: 2026-10-02 10:47:08.845589

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a4ae1ae2cbe2"
down_revision: str | Sequence[str] | None = "c4e5f6a7b8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
