"""add team and team_member

Revision ID: bc466a293297
Revises: 04fcb161b253
Create Date: 2026-01-09 17:29:00.920254

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bc466a293297"
down_revision: str | Sequence[str] | None = "04fcb161b253"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
