"""Add zalo_bot_id and zalo_bind_code to users

Revision ID: bcb89e1b71aa
Revises: c2aef165dfa2
Create Date: 2026-02-25 21:21:18.955579

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bcb89e1b71aa"
down_revision: Union[str, Sequence[str], None] = "c2aef165dfa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_api_keys_key_hash"), table_name="role_api_keys")
    op.drop_index(op.f("ix_role_api_keys_prefix"), table_name="role_api_keys")
    op.drop_table("role_api_keys")
    op.add_column(
        "users",
        sa.Column(
            "zalo_bot_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "zalo_bind_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_users_zalo_bind_code"), "users", ["zalo_bind_code"], unique=False
    )
    op.create_index(
        op.f("ix_users_zalo_bot_id"), "users", ["zalo_bot_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_zalo_bot_id"), table_name="users")
    op.drop_index(op.f("ix_users_zalo_bind_code"), table_name="users")
    op.drop_column("users", "zalo_bind_code")
    op.drop_column("users", "zalo_bot_id")
    op.create_table(
        "role_api_keys",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("key_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("prefix", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("role_api_keys_role_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("role_api_keys_pkey")),
    )
    op.create_index(
        op.f("ix_role_api_keys_prefix"), "role_api_keys", ["prefix"], unique=False
    )
    op.create_index(
        op.f("ix_role_api_keys_key_hash"), "role_api_keys", ["key_hash"], unique=False
    )
    # ### end Alembic commands ###
