"""add billing table

Revision ID: c0a1670f2d91
Revises: 823b59b28035
Create Date: 2026-04-04 05:11:35.109368

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c0a1670f2d91"
down_revision: str | Sequence[str] | None = "823b59b28035"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
