"""description

Revision ID: c24723e43a40
Revises: b5eca9e80dcc
Create Date: 2026-01-07 20:24:48.902669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c24723e43a40"
down_revision: Union[str, Sequence[str], None] = "b5eca9e80dcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bonus_points",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column(
            "reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bonus_points_date"), "bonus_points", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_bonus_points_user_id"), "bonus_points", ["user_id"], unique=False
    )
    op.create_table(
        "permission_requests",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("ABSENCE", "POSTPONE", "LATE", "OTHER", name="requestcategory"),
            nullable=False,
        ),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_permission_requests_category"),
        "permission_requests",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_requests_user_id"),
        "permission_requests",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "violations",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "reason", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_violations_date"), "violations", ["date"], unique=False)
    op.create_index(
        op.f("ix_violations_user_id"), "violations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_violations_user_id"), table_name="violations")
    op.drop_index(op.f("ix_violations_date"), table_name="violations")
    op.drop_table("violations")
    op.drop_index(
        op.f("ix_permission_requests_user_id"), table_name="permission_requests"
    )
    op.drop_index(
        op.f("ix_permission_requests_category"), table_name="permission_requests"
    )
    op.drop_table("permission_requests")
    op.drop_index(op.f("ix_bonus_points_user_id"), table_name="bonus_points")
    op.drop_index(op.f("ix_bonus_points_date"), table_name="bonus_points")
    op.drop_table("bonus_points")
    # ### end Alembic commands ###
