"""add check_out_at to meeting_participants

Revision ID: cce51408a625
Revises: 88fd33baf664
Create Date: 2026-05-07 10:36:01.994479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cce51408a625"
down_revision: Union[str, Sequence[str], None] = "88fd33baf664"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meeting_participants", sa.Column("check_out_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meeting_participants", "check_out_at")
    # ### end Alembic commands ###
