"""create_user_roles_table

Revision ID: fb41d35d7be2
Revises: 4405c56add67
Create Date: 2026-07-03 04:54:10.628598

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb41d35d7be2"
down_revision: str | Sequence[str] | None = "4405c56add67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_roles_created_at"), "user_roles", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False
    )

    # Data migration: Copy existing role assignments
    op.execute("""
        INSERT INTO user_roles (user_id, role_id, created_at, updated_at, is_deleted)
        SELECT id, role_id, NOW(), NOW(), FALSE
        FROM users
        WHERE role_id IS NOT NULL
    """)

    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_constraint("users_role_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key("users_role_id_fkey", "users", "roles", ["role_id"], ["id"])
    op.create_index("ix_users_role_id", "users", ["role_id"], unique=False)

    # Data migration rollback: Restore role_id from user_roles
    op.execute("""
        UPDATE users
        SET role_id = (
            SELECT role_id 
            FROM user_roles 
            WHERE user_roles.user_id = users.id 
            LIMIT 1
        )
    """)

    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_created_at"), table_name="user_roles")
    op.drop_table("user_roles")
    # ### end Alembic commands ###
